/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Clases.*;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ASUS
 */
public class Problema_3 extends javax.swing.JFrame {
    private Principal v1;
    /**
     * Creates new form Problema_3
     */
    public Problema_3() {
        initComponents();
    }

    public Problema_3(Principal aThis) {
        initComponents();
        this.v1=aThis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnAtras = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Pantalla_interfaz = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        campoCiX = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnAtras.setText("ATRAS");
        BtnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 383, 80, 34));

        btnMostrar.setText("MOSTRAR");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 84, 34));

        jScrollPane1.setViewportView(Pantalla_interfaz);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 450, 250));

        jLabel1.setText("CI x");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));
        getContentPane().add(campoCiX, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 180, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasActionPerformed
        // TODO add your handling code here:
        this.v1.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BtnAtrasActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        String ciX = campoCiX.getText().trim();
        String titulos[] = { "ID Medico","Nombre del Medico", "Especialidad"};
        DefaultTableModel pantalla = new DefaultTableModel(null, titulos);
        NodoP R = v1.getA().getLp().getP();
		String idpacientebuscado = "";
		LD_NormalD x = new LD_NormalD();
		System.out.println("Medicos que atendieron la paciente con ci: " + ciX);
		while(R != null) {
			if(R.getP().getCi().equals(ciX)) {
				idpacientebuscado = R.getP().getId_paciente();
			}
			R = R.getSig();
		}
		
		NodoH S = v1.getA().getLh().getP();
		while(S != null) {
			if(S.getH().getId_paciente().equals(idpacientebuscado)) {
				x = S.getH().getLd();
			}
			S = S.getSig();
		}
		
		NodoD T = x.getP();
		while(T != null) {
			String idMedico = T.getD().getId_medico();
			PilaM aux1 = new PilaM();
			while(!v1.getA().getPm().esVacia()) {
				Medico z = v1.getA().getPm().eli();
				if(z.getId_medico().equals(idMedico)) {
					System.out.println("----------------");
					System.out.println("nombre del medico: " + z.getNombre());
					System.out.println("especialidad: " + z.getEspecialidad());
                                        String fila [] = {z.getId_medico(),z.getNombre(),z.getEspecialidad()};
                                        pantalla.addRow(fila);
                                        
				}
				aux1.adi(z);
			}
			v1.getA().getPm().vaciar(aux1);
			T = T.getSig();
                        Pantalla_interfaz.setModel(pantalla);
		}
                
    }//GEN-LAST:event_btnMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Problema_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Problema_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Problema_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Problema_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Problema_3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtras;
    private javax.swing.JTable Pantalla_interfaz;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JTextField campoCiX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
