/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Clases.LD_NormalD;
import Clases.NodoD;
import Clases.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Problema_2 extends javax.swing.JFrame {
    private Principal v1;
    /**
     * Creates new form Problema_2
     */
    public Problema_2() {
        initComponents();
    }

    public Problema_2(Principal aThis) {
        initComponents();
        this.v1=aThis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        campoSintoma = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Pantalla_interfaz = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        campoTratamiento = new javax.swing.JTextField();
        btnMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAtras.setText("ATRAS");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 108, 42));

        jLabel1.setText("SINTOMA X");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 87, 35));

        campoSintoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSintomaActionPerformed(evt);
            }
        });
        getContentPane().add(campoSintoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 180, 40));

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 100, 40));

        Pantalla_interfaz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Pantalla_interfaz);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 350, 220));

        jLabel2.setText("tratamiento agregar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        campoTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTratamientoActionPerformed(evt);
            }
        });
        getContentPane().add(campoTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 180, 40));

        btnMostrar.setText("MOSTRAR");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 70, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        this.v1.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void campoSintomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSintomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSintomaActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        String SintomaX = campoSintoma.getText().trim();
        String Tratamiento = campoTratamiento.getText().trim();
        NodoH R = v1.getA().getLh().getP();
        while (R != null) {
            LD_NormalD ld = R.getH().getLd();
            NodoD S = ld.getP();
            while (S != null) {
                if (S.getD().getSintomas().equals(SintomaX)) {
                    if(Tratamiento.equals("")){
                       S.getD().setTratamiento("Fisioterapia");
                    }else{
                        S.getD().setTratamiento(Tratamiento);
                    }
                    System.out.println("modificacion");
                    System.out.println("id_medico: " + S.getD().getId_medico());
                    System.out.println("sintomas: " + S.getD().getSintomas());
                    System.out.println("tratamieno: " + S.getD().getTratamiento());
                }
                S = S.getSig();
            }
            R = R.getSig();
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void campoTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTratamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTratamientoActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        String titulos[] = {"ID medico", "Sintomas", "tratamiento"};
        DefaultTableModel pantalla = new DefaultTableModel(null, titulos);
        NodoH R = v1.getA().getLh().getP();
        while (R != null) {
            LD_NormalD ld = R.getH().getLd();
            NodoD S = ld.getP();
            while (S != null) {
                System.out.println("modificacion");
                System.out.println("id_medico: " + S.getD().getId_medico());
                System.out.println("sintomas: " + S.getD().getSintomas());
                System.out.println("tratamieno: " + S.getD().getTratamiento());
                String fila [] = {S.getD().getId_medico(),S.getD().getSintomas(),S.getD().getTratamiento()};
                pantalla.addRow(fila);
                System.out.println("---------------------------------");
                S = S.getSig();
            }
            R = R.getSig();
            Pantalla_interfaz.setModel(pantalla);
        }
    }//GEN-LAST:event_btnMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Problema_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Problema_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Problema_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Problema_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Problema_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Pantalla_interfaz;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JTextField campoSintoma;
    private javax.swing.JTextField campoTratamiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
