package Ventanas;

import Clases.*;
import javax.swing.table.DefaultTableModel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class Problema_4 extends javax.swing.JFrame {
    private Principal v1;
    /**
     * Creates new form Problema_4
     */
    public Problema_4() {
        initComponents();
    }

    public Problema_4(Principal aThis) {
        initComponents();
        this.v1=aThis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        campoPaciente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoConusultorio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Pantalla_interfaz = new javax.swing.JTable();
        btnMover = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("ATRAS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 357, 94, 37));

        jLabel1.setText("ID paciente en Espera X");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        campoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(campoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 150, 40));

        jLabel2.setText("ID consultorio Y");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));
        getContentPane().add(campoConusultorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 150, 40));

        jScrollPane1.setViewportView(Pantalla_interfaz);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 430, 230));

        btnMover.setText("LLEVARLO AL PRINCIPIO");
        btnMover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoverActionPerformed(evt);
            }
        });
        getContentPane().add(btnMover, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        btnMostrar.setText("MOSTRAR");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 100, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.v1.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void campoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPacienteActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        String titulos[] = { "Datos del Consultorio"};
        DefaultTableModel pantalla = new DefaultTableModel(null, titulos);
        ColaCircularC aux1 = new ColaCircularC();
        while (!v1.getA().getCc().esVacia()) {
            Consultorio cst = v1.getA().getCc().eli();
            String fila [] = {"------CONSULTORIO-------"};
            pantalla.addRow(fila);
            String fila1 [] = {"ID Consultorio"+cst.getId_consultorio()};
            pantalla.addRow(fila1);
            String fila2 [] = {"ID Medico"+cst.getId_medico()};
            pantalla.addRow(fila2);
            ColaSimpleIn colap = cst.getCin();  
            ColaSimpleIn aux2 = new ColaSimpleIn();
            String fila33 [] = {"_______COLA DE INGRESO_____"};
            pantalla.addRow(fila33);
            while(!colap.esVacia()){
                PacienteEnEspera x = colap.eli();
                String fila3 [] = {"ID Paciente"+x.getId_paciente()};
                pantalla.addRow(fila3);
                String fila4 [] = {"Sintomas"+x.getSintomas()};
                pantalla.addRow(fila4);
                
                String fila44 [] = {""};
                pantalla.addRow(fila44);
                aux2.adi(x);
            }
            String fila333 [] = {"-*-*-*-*-*-*-*-*-*-*-*"};
            pantalla.addRow(fila333);
            colap.vaciar(aux2);
            /*if (cst.getId_consultorio().equals(idConsultorioY)) {
                ColaSimpleIn colap = cst.getCin();
                ColaSimpleIn aux2 = new ColaSimpleIn();
                ColaSimpleIn aux3 = new ColaSimpleIn();
                while (!colap.esVacia()) {
                    PacienteEnEspera x = colap.eli();
                    if (x.getId_paciente().equals(idPacienteEnEsperaX)) {
                        aux3.adi(x);
                    } else {
                        aux2.adi(x);
                    }
                }
                colap.vaciar(aux3);
                colap.vaciar(aux2);
            }*/
            aux1.adi(cst);
            Pantalla_interfaz.setModel(pantalla);
        }
        v1.getA().getCc().vaciar(aux1);
        
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnMoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoverActionPerformed
        // TODO add your handling code here:
        String idConsultorioY = campoConusultorio.getText().strip();
        String idPacienteEnEsperaX = campoPaciente.getText().strip();
        
        ColaCircularC aux1 = new ColaCircularC();

        while (!v1.getA().getCc().esVacia()) {
            Consultorio cst = v1.getA().getCc().eli();
            if (cst.getId_consultorio().equals(idConsultorioY)) {
                ColaSimpleIn colap = cst.getCin();
                ColaSimpleIn aux2 = new ColaSimpleIn();
                ColaSimpleIn aux3 = new ColaSimpleIn();
                while (!colap.esVacia()) {
                    PacienteEnEspera x = colap.eli();
                    if (x.getId_paciente().equals(idPacienteEnEsperaX)) {
                        aux3.adi(x);
                    } else {
                        aux2.adi(x);
                    }
                }
                colap.vaciar(aux3);
                colap.vaciar(aux2);
            }
            aux1.adi(cst);
        }
        v1.getA().getCc().vaciar(aux1);
    }//GEN-LAST:event_btnMoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Problema_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Problema_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Problema_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Problema_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Problema_4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Pantalla_interfaz;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnMover;
    private javax.swing.JTextField campoConusultorio;
    private javax.swing.JTextField campoPaciente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
