/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;
import Clases.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ASUS
 */
public class Problema_5 extends javax.swing.JFrame {
    private Principal v1;
    /**
     * Creates new form Problema_5
     */
    public Problema_5() {
        initComponents();
    }

    public Problema_5(Principal aThis) {
        initComponents();
        this.v1=aThis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnVeificar = new javax.swing.JButton();
        campoEspecialidadX = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Pantalla_interfaz = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("ATRAS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 91, 46));

        btnVeificar.setText("verificar");
        btnVeificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVeificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 100, 30));

        campoEspecialidadX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEspecialidadXActionPerformed(evt);
            }
        });
        getContentPane().add(campoEspecialidadX, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 160, 40));

        jLabel1.setText("Especialidad X");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jScrollPane1.setViewportView(Pantalla_interfaz);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 410, 210));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("EXCESO DE PACIENTES MOVER A OTRO CONSULTORIO SI EXISTIERA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.v1.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnVeificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeificarActionPerformed
        // TODO add your handling code here:
        String especialidadX = campoEspecialidadX.getText().trim();
        ColaCircularC aux1 = new ColaCircularC();
        ColaSimpleIn pacientesExtra = new ColaSimpleIn();
        String idDelConsultorioLleno = "";
        boolean sw = true;

        while (!v1.getA().getCc().esVacia()) {
            Consultorio consultorio = v1.getA().getCc().eli();
            String idMedico = consultorio.getId_medico();
            PilaM aux2 = new PilaM();
            while (!v1.getA().getPm().esVacia()) {
                Medico medico = v1.getA().getPm().eli();
                if (medico.getEspecialidad().equals(especialidadX)
                        && medico.getId_medico().equals(idMedico)) {
                    ColaSimpleIn colaPacientes = consultorio.getCin();
                    ColaSimpleIn aux3 = new ColaSimpleIn();
                    int nroPacientes = colaPacientes.nroElem();
                    if (nroPacientes > 5) {
                        for (int i = 0; i < nroPacientes - 1; i++) {
                            PacienteEnEspera x = colaPacientes.eli();
                            aux3.adi(x);
                        }
                        pacientesExtra.vaciar(colaPacientes);
                        colaPacientes.vaciar(aux3);
                        idDelConsultorioLleno = consultorio.getId_consultorio();

                    }
                }
                aux2.adi(medico);
            }
            v1.getA().getPm().vaciar(aux2);
            aux1.adi(consultorio);
        }
        v1.getA().getCc().vaciar(aux1);

        while (!v1.getA().getCc().esVacia()) {
            Consultorio consultorio = v1.getA().getCc().eli();
            String idMedico = consultorio.getId_medico();
            if (consultorio.getId_consultorio() != idDelConsultorioLleno) {
                PilaM aux5 = new PilaM();
                while (!v1.getA().getPm().esVacia()) {
                    Medico medico = v1.getA().getPm().eli();
                    //System.out.println("*MEDICO*"+medico.getNombre()+" "+medico.getEspecialidad());
                    if (idMedico == medico.getId_medico() && medico.getEspecialidad().equals(especialidadX)) {
                        
                        consultorio.getCin().vaciar(pacientesExtra);
                        sw = false;
                    }
                    aux5.adi(medico);
                }
                //System.out.println("--------------------------");
                v1.getA().getPm().vaciar(aux5);
            }
            aux1.adi(consultorio);
        }
        v1.getA().getCc().vaciar(aux1);

        if (sw) {
            System.out.println("\rSolo existe un consultorio con la especialidad " + especialidadX);
            mostrarTabla(v1,especialidadX);
            JOptionPane.showMessageDialog(null, "Solo existe un consultorio con la especialidad " + especialidadX);
            while (!v1.getA().getCc().esVacia()) {
                Consultorio consultorio = v1.getA().getCc().eli();
                if (consultorio.getId_consultorio().equals(idDelConsultorioLleno)) {
                    consultorio.getCin().vaciar(pacientesExtra);
                }
            }
        }
        mostrarTabla(v1,especialidadX);
        /*---------------------------------------
        String titulos[] = { "ID Consultorio","ID Medico","Nombre del Medico", "Especialidad"};
        DefaultTableModel pantalla = new DefaultTableModel(null, titulos);
        while (!v1.getA().getCc().esVacia()) {
            Consultorio cons = v1.getA().getCc().eli();
            System.out.println("consul====>" + cons.getId_consultorio());
            PilaM auxi = new PilaM();
            while (!v1.getA().getPm().esVacia()) {
                Medico medico = v1.getA().getPm().eli();
                if (cons.getId_medico().equals(medico.getId_medico())) {
                    if (medico.getEspecialidad().equals(especialidadX)) {
                        System.out.println("Medi " + medico.getNombre() + " " + medico.getEspecialidad());
                        String fila [] = {cons.getId_consultorio(),medico.getId_medico(),medico.getNombre(),medico.getEspecialidad()};
                        pantalla.addRow(fila);
                    }
                }
                auxi.adi(medico);
            }
            v1.getA().getPm().vaciar(auxi);
            aux1.adi(cons);
            Pantalla_interfaz.setModel(pantalla);
        }
        v1.getA().getCc().vaciar(aux1);
        //---------------------------------------*/
    }//GEN-LAST:event_btnVeificarActionPerformed

    private void campoEspecialidadXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEspecialidadXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEspecialidadXActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Problema_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Problema_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Problema_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Problema_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Problema_5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Pantalla_interfaz;
    private javax.swing.JButton btnVeificar;
    private javax.swing.JTextField campoEspecialidadX;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void mostrarTabla(Ventanas.Principal v1, String especialidadX) {
        ColaCircularC aux1 = new ColaCircularC();
        //---------------------------------------
        String titulos[] = { "ID Consultorio","ID Medico","Nombre del Medico", "Especialidad"};
        DefaultTableModel pantalla = new DefaultTableModel(null, titulos);
        while (!v1.getA().getCc().esVacia()) {
            Consultorio cons = v1.getA().getCc().eli();
            System.out.println("consul====>" + cons.getId_consultorio());
            PilaM auxi = new PilaM();
            while (!v1.getA().getPm().esVacia()) {
                Medico medico = v1.getA().getPm().eli();
                if (cons.getId_medico().equals(medico.getId_medico())) {
                    if (medico.getEspecialidad().equals(especialidadX)) {
                        System.out.println("Medi " + medico.getNombre() + " " + medico.getEspecialidad());
                        String fila [] = {cons.getId_consultorio(),medico.getId_medico(),medico.getNombre(),medico.getEspecialidad()};
                        pantalla.addRow(fila);
                    }
                }
                auxi.adi(medico);
            }
            v1.getA().getPm().vaciar(auxi);
            aux1.adi(cons);
            Pantalla_interfaz.setModel(pantalla);
        }
        v1.getA().getCc().vaciar(aux1);
        //---------------------------------------
    }
}
