/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Clases.Historial;
import Clases.LD_NormalD;
import Clases.NodoH;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Problema_1 extends javax.swing.JFrame {
    private Principal v1;
    /**
     * Creates new form Problema_1
     */
    public Problema_1() {
        initComponents();
    }

    public Problema_1(Principal aThis) {
        initComponents();
        this.v1=aThis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVerifica = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        campoIDX = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        resultText = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVerifica.setText("VERIFICA");
        btnVerifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificaActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerifica, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 137, 40));

        btnAtras.setText("ATRAS");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, 94, 47));

        campoIDX.setText(" ");
        campoIDX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIDXActionPerformed(evt);
            }
        });
        getContentPane().add(campoIDX, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 170, 30));

        jLabel1.setText("Ingresar ID del paciente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 80, 140, 20));

        resultText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(resultText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 420, 80));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Verifica si el paciente tiene mas de un diagnostico");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 590, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        this.v1.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void campoIDXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIDXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIDXActionPerformed

    private void btnVerificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificaActionPerformed
        // TODO add your handling code here:
        try {
            String idX = campoIDX.getText().trim();
            String text = "";
            NodoH R = v1.getA().getLh().getP();
            boolean sw = false;
            while (R != null) {
                Historial x = R.getH();
                LD_NormalD ld = x.getLd();
                System.out.println("Comparando: [" + x.getId_paciente() + "] vs [" + idX + "]");
                ld.mostrar();
                if (x.getId_paciente().equals(idX)) {
                    if (ld.nroNodos() > 1) {
                        System.out.println("paciente con id " + idX + " tiene mas de un diagnostico");
                        text = "paciente con id " + idX + " tiene mas de un diagnostico";
                        resultText.setText(text);
                        sw = true;
                        break;
                    }else{
                        System.out.print("paciente con id" + idX + " tiene solo un diagnostico");
                        text = "paciente con id" + idX + " tiene solo un diagnostico";
                        resultText.setText(text);
                        sw = true;
                    }
                }
                R = R.getSig();
            }
            if (!sw) {
                System.out.println("paciente con id  " + idX + " no encontrado");
                text = "paciente con id  " + idX + " no encontrado";
                resultText.setText(text);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "coloque datos validos");
        }
    }//GEN-LAST:event_btnVerificaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Problema_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Problema_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Problema_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Problema_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Problema_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnVerifica;
    private javax.swing.JTextField campoIDX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel resultText;
    // End of variables declaration//GEN-END:variables
}
